services:
  server:
    container_name: express-app
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"

  client:
    container_name: next-app
    build: ./client
    env_file:
      - ./client/.env
    depends_on:
      - server
    ports:
      - "5000:3000"